var TAFFY;

if (typeof exports === "object") TAFFY = require("../../lib/taffy").taffy;

this.armors = new TAFFY([
  {
    name: "Padded",
    cost: "5 gp",
    bon: 1,
    max_dex_bonus: 8,
    acp: 0,
    spell_fail: "5%",
    speed30: "30",
    speed20: "20",
    weight: 10,
    category: "light",
    type: "armor",
    tags: ["pathfinder"],
    _id: "ce4b"
  }, {
    name: "Leather",
    cost: "10 gp",
    bon: 2,
    max_dex_bonus: 6,
    acp: 0,
    spell_fail: "10%",
    speed30: "30",
    speed20: "20",
    weight: 15,
    category: "light",
    type: "armor",
    tags: ["pathfinder"],
    _id: "22d2"
  }, {
    name: "Studded leather",
    cost: "25 gp",
    bon: 3,
    max_dex_bonus: 5,
    acp: -1,
    spell_fail: "15%",
    speed30: "30",
    speed20: "20",
    weight: 20,
    category: "light",
    type: "armor",
    tags: ["pathfinder"],
    _id: "b81b"
  }, {
    name: "Chain shirt",
    cost: "100 gp",
    bon: 4,
    max_dex_bonus: 4,
    acp: -2,
    spell_fail: "20%",
    speed30: "30",
    speed20: "20",
    weight: 25,
    category: "light",
    type: "armor",
    tags: ["pathfinder"],
    _id: "d1b3"
  }, {
    name: "Hide",
    cost: "15 gp",
    bon: 3,
    max_dex_bonus: 4,
    acp: -3,
    spell_fail: "20%",
    speed30: "20",
    speed20: "15",
    weight: 25,
    category: "medium",
    type: "armor",
    tags: ["pathfinder"],
    _id: "b2a2"
  }, {
    name: "Scale mail",
    cost: "50 gp",
    bon: 4,
    max_dex_bonus: 3,
    acp: -4,
    spell_fail: "25%",
    speed30: "20",
    speed20: "15",
    weight: 30,
    category: "medium",
    type: "armor",
    tags: ["pathfinder"],
    _id: "2943"
  }, {
    name: "Chainmail",
    cost: "150 gp",
    bon: 5,
    max_dex_bonus: 2,
    acp: -5,
    spell_fail: "30%",
    speed30: "20",
    speed20: "15",
    weight: 40,
    category: "medium",
    type: "armor",
    tags: ["pathfinder"],
    _id: "f5c2"
  }, {
    name: "Breastplate",
    cost: "200 gp",
    bon: 5,
    max_dex_bonus: 3,
    acp: -4,
    spell_fail: "25%",
    speed30: "20",
    speed20: "15",
    weight: 30,
    category: "medium",
    type: "armor",
    tags: ["pathfinder"],
    _id: "f519"
  }, {
    name: "Splint mail",
    cost: "200 gp",
    bon: 6,
    max_dex_bonus: 0,
    acp: -7,
    spell_fail: "40%",
    speed30: "20",
    speed20: "15",
    weight: 45,
    category: "heavy",
    type: "armor",
    tags: ["pathfinder"],
    _id: "f962"
  }, {
    name: "Banded mail",
    cost: "250 gp",
    bon: 6,
    max_dex_bonus: 1,
    acp: -6,
    spell_fail: "35%",
    speed30: "20",
    speed20: "15",
    weight: 35,
    category: "heavy",
    type: "armor",
    tags: ["pathfinder"],
    _id: "7be5"
  }, {
    name: "Half-plate",
    cost: "600 gp",
    bon: 7,
    max_dex_bonus: 0,
    acp: -7,
    spell_fail: "40%",
    speed30: "20",
    speed20: "15",
    weight: 50,
    category: "heavy",
    type: "armor",
    tags: ["pathfinder"],
    _id: "3afd"
  }, {
    name: "Full plate",
    cost: "1,500 gp",
    bon: 8,
    max_dex_bonus: 1,
    acp: -6,
    spell_fail: "35%",
    speed30: "20",
    speed20: "15",
    weight: 50,
    category: "heavy",
    type: "armor",
    tags: ["pathfinder"],
    _id: "90df"
  }, {
    name: "Armor spikes",
    cost: "50 gp",
    bon: "-",
    max_dex_bonus: "-",
    acp: 0,
    spell_fail: "-",
    speed30: "-",
    speed20: "-",
    weight: 10,
    type: "armor",
    tags: ["pathfinder"],
    _id: "5a59"
  }, {
    name: "Gauntlet, locked",
    cost: "8 gp",
    bon: "-",
    max_dex_bonus: "-",
    acp: "Special",
    spell_fail: "-",
    speed30: "-",
    speed20: "-",
    weight: 5,
    type: "armor",
    tags: ["pathfinder"],
    _id: "9803"
  }, {
    name: "Shield spikes",
    cost: "10 gp",
    bon: "-",
    max_dex_bonus: "-",
    acp: 0,
    spell_fail: "-",
    speed30: "-",
    speed20: "-",
    weight: 5,
    type: "armor",
    tags: ["pathfinder"],
    _id: "fb80"
  }
]);
